apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-deployment
spec:
  selector:
    matchLabels:
      app: internal
  replicas: 3
  template:
    metadata:
      labels:
        app: internal
    spec:
      containers:
      - name: internal
        image: beachcoder/internal
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
